//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD_TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int ctid { get; set; }
        public string name { get; set; }
        public Nullable<int> sid { get; set; }
    
        public virtual State State { get; set; }
    }
}
