//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD_TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Img
    {
        public int imgid { get; set; }
        public string imgpath { get; set; }
        public string imgdesc { get; set; }
    }
}
