//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD_TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Std_dt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Std_dt()
        {
            this.Sec_dt = new HashSet<Sec_dt>();
        }
    
        public int stdid { get; set; }
        public string stdname { get; set; }
        public string stdadr { get; set; }
        public string stdphno { get; set; }
        public Nullable<int> stdpin { get; set; }
        public string stdcity { get; set; }
        public string stdgen { get; set; }
        public string stdpic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sec_dt> Sec_dt { get; set; }
    }
}
