//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD_TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetails
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Roll { get; set; }
        public string Stream { get; set; }
        public string City { get; set; }
        public string Gender { get; set; }
    }
}
